#ifndef EAGOLD_R4_R5_R7_LIFECYCLE_MQH
#define EAGOLD_R4_R5_R7_LIFECYCLE_MQH
// Rules R4/R5/R7 — realization, basket close, restart and pending trail.
bool GetLatestActivatedPosition(int direction,double &latestPrice,double &latestLot,int &latestTicket){int type=(direction==OP_BUY?OP_BUY:OP_SELL);latestPrice=0.0;latestLot=NormalizeLot(Lot);latestTicket=-1;datetime latestTime=0;bool found=false;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;datetime t=OrderOpenTime();int ticket=OrderTicket();if(!found||t>latestTime||(t==latestTime&&ticket>latestTicket)){found=true;latestTime=t;latestPrice=OrderOpenPrice();latestLot=OrderLots();latestTicket=ticket;}}return(found);}
bool HasRecoveryPending(int direction){string tag=(direction==OP_BUY?"EAGOLD BUY RECOVERY":"EAGOLD SELL RECOVERY");int type=(direction==OP_BUY?OP_BUYSTOP:OP_SELLSTOP);for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;if(StringFind(OrderComment(),tag,0)>=0)return(true);}return(false);}
double NextRecoveryLot(double previousLot){if(previousLot<=0.0)return(NormalizeLot(Lot));return(NormalizeLot(previousLot*Multiplier+LotIncrement));}
bool CanCloseLightBasket(int direction){double b=DirectionLots(OP_BUY),s=DirectionLots(OP_SELL);if(b==s)return(true);if(direction==OP_BUY&&b<s&&s>0.0)return(false);if(direction==OP_SELL&&s<b&&b>0.0)return(false);return(true);}
bool CloseDirectionPositionsRobust(int direction){int type=(direction==OP_BUY?OP_BUY:OP_SELL);int tickets[];ArrayResize(tickets,0);for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;int n=ArraySize(tickets);ArrayResize(tickets,n+1);tickets[n]=OrderTicket();}bool ok=true;for(int j=0;j<ArraySize(tickets);j++){if(!CloseMarketOrder(tickets[j]))ok=false;}return(ok&&CountDirectionPositions(direction)==0);}
void BuySingleTakeProfit(){if(CountDirectionPositions(OP_BUY)!=1)return;if(!CanCloseLightBasket(OP_BUY))return;if(!R10RecoveryAllowBasketClose(OP_BUY))return;if(DirectionBasketProfit(OP_BUY)<TakeProfit)return;int ticket=-1;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(IsEAGOLDOrder()&&OrderType()==OP_BUY){ticket=OrderTicket();break;}}if(ticket>0&&CloseMarketOrder(ticket)){CloseAllDirectionPending(OP_BUY);SendPending(OP_BUYSTOP,Ask+PointsToPrice(MiniGrid1),Lot,"EAGOLD R4 BUY NEXT");Print(EA_NAME," RULE 4 BUY TP REENTRY. closed=",ticket);CreateEngineActionMarker("R4","REALIZE",OP_BUY,Lot);}}
void SellSingleTakeProfit(){if(CountDirectionPositions(OP_SELL)!=1)return;if(!CanCloseLightBasket(OP_SELL))return;if(!R10RecoveryAllowBasketClose(OP_SELL))return;if(DirectionBasketProfit(OP_SELL)<TakeProfit)return;int ticket=-1;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(IsEAGOLDOrder()&&OrderType()==OP_SELL){ticket=OrderTicket();break;}}if(ticket>0&&CloseMarketOrder(ticket)){CloseAllDirectionPending(OP_SELL);SendPending(OP_SELLSTOP,Bid-PointsToPrice(MiniGrid2),Lot,"EAGOLD R4 SELL NEXT");Print(EA_NAME," RULE 4 SELL TP REENTRY. closed=",ticket);CreateEngineActionMarker("R4","REALIZE",OP_SELL,Lot);}}
bool BuyBasketTargetReached(){int count=CountDirectionPositions(OP_BUY);if(count<=1||TakeProfit<=0.0)return(false);return(DirectionBasketProfit(OP_BUY)>=count*TakeProfit);}
bool SellBasketTargetReached(){int count=CountDirectionPositions(OP_SELL);if(count<=1||TakeProfit<=0.0)return(false);return(DirectionBasketProfit(OP_SELL)>=count*TakeProfit);}
void TrailAllStopOrders(){if(PendingStepTrail<=0.0)return;double stopLevel=MarketInfo(Symbol(),MODE_STOPLEVEL)*Point;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder())continue;int type=OrderType();if(type!=OP_BUYSTOP&&type!=OP_SELLSTOP)continue;string c=OrderComment();double resetPoints=0.0,triggerPoints=PendingStepTrail;string family="GLOBAL";if(StringFind(c,"EAGOLD R1 FIRST",0)>=0){resetPoints=FirstStep;triggerPoints=FirstStep+PendingStepTrail;family="R1 FIRST";}else if(StringFind(c,"EAGOLD BUY RECOVERY",0)>=0||StringFind(c,"EAGOLD SELL RECOVERY",0)>=0){resetPoints=RecoveryMinDistance;family="RECOVERY";}else if(StringFind(c,"EAGOLD R4 BUY NEXT",0)>=0){resetPoints=MiniGrid1;family="R4 BUY";}else if(StringFind(c,"EAGOLD R4 SELL NEXT",0)>=0){resetPoints=MiniGrid2;family="R4 SELL";}else if(StringFind(c,"EAGOLD R7 RESTART",0)>=0){resetPoints=BasketRestartStep;family="R7 RESTART";}else{double marketDistance=(type==OP_BUYSTOP?OrderOpenPrice()-Ask:Bid-OrderOpenPrice());if(marketDistance<=0.0)continue;resetPoints=marketDistance/Point;family="GLOBAL UNKNOWN";}if(resetPoints<=0.0||triggerPoints<=0.0)continue;double trigger=PointsToPrice(triggerPoints),resetDistance=PointsToPrice(resetPoints);RefreshRates();double current=OrderOpenPrice(),desired=current,adverseDistance=0.0;int ticket=OrderTicket();if(type==OP_BUYSTOP){adverseDistance=current-Ask;if(adverseDistance<trigger)continue;desired=NormalizePrice(Ask+resetDistance);if(desired>=current||desired<=Ask+stopLevel)continue;}else{adverseDistance=Bid-current;if(adverseDistance<trigger)continue;desired=NormalizePrice(Bid-resetDistance);if(desired<=current||desired>=Bid-stopLevel)continue;}ResetLastError();if(!OrderModify(ticket,desired,0,0,0,clrNONE))Print(EA_NAME," GLOBAL STOP TRAIL FAILED ticket=",ticket," family=",family," error=",GetLastError());else Print(EA_NAME," GLOBAL STOP TRAIL ticket=",ticket," family=",family," old=",DoubleToString(current,Digits)," new=",DoubleToString(desired,Digits)," adverse=",DoubleToString(adverseDistance/Point,1)," trigger=",DoubleToString(triggerPoints,1)," reset=",DoubleToString(resetPoints,1));}}
void RestartEmptyBasket(int direction){if(BasketRestartStep<=0.0)return;if(CountDirectionPositions(direction)!=0||CountDirectionPending(direction)!=0)return;RefreshRates();if(direction==OP_BUY){int r7ticket=SendPending(OP_BUYSTOP,Ask+PointsToPrice(BasketRestartStep),Lot,"EAGOLD R7 RESTART BUY");if(r7ticket>0)CreateEngineActionMarker("R7","RESTART",OP_BUY,Lot);}else{int r7ticket=SendPending(OP_SELLSTOP,Bid-PointsToPrice(BasketRestartStep),Lot,"EAGOLD R7 RESTART SELL");if(r7ticket>0)CreateEngineActionMarker("R7","RESTART",OP_SELL,Lot);}}
#endif
