#ifndef EAGOLD_R9_HEDGE_MQH
#define EAGOLD_R9_HEDGE_MQH
// Rule R9 — exposure hedge controller.
bool IntArrayContains(int &arr[],int ticket){for(int i=0;i<ArraySize(arr);i++)if(arr[i]==ticket)return(true);return(false);}
void IntArrayAdd(int &arr[],int ticket){if(ticket<0||IntArrayContains(arr,ticket))return;int n=ArraySize(arr);ArrayResize(arr,n+1);arr[n]=ticket;}
bool R9Processed(int ticket){return(IntArrayContains(g_r9ProcessedTickets,ticket));}
void R9MarkProcessed(int ticket){IntArrayAdd(g_r9ProcessedTickets,ticket);}
void R9SeedExistingPositions(){for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder())continue;int type=OrderType();if(type==OP_BUY||type==OP_SELL)R9MarkProcessed(OrderTicket());}}
bool R9GetNewExposureState(int &lightDirection,double &exposure,double &lightLots,double &heavyLots){double b=DirectionLots(OP_BUY),s=DirectionLots(OP_SELL);exposure=MathAbs(b-s);lightDirection=-1;lightLots=MathMin(b,s);heavyLots=MathMax(b,s);if(exposure<R9ExposureTriggerLots)return(false);if(b<s)lightDirection=OP_BUY;else if(s<b)lightDirection=OP_SELL;else return(false);return(true);}
bool R9HedgeFromActivatedTicket(int ticket){if(!EnableR9Hedge)return(false);if(!OrderSelect(ticket,SELECT_BY_TICKET,MODE_TRADES))return(false);if(!IsEAGOLDOrder())return(false);int type=OrderType();if(type!=OP_BUY&&type!=OP_SELL)return(false);double triggerLot=OrderLots();int light=-1;double exposure=0.0,lightLots=0.0,heavyLots=0.0;if(!R9GetNewExposureState(light,exposure,lightLots,heavyLots)){g_r9HedgeActive=false;return(false);}int heavy=HeavyDirection();if(type!=heavy)return(false);double hedgeLot=NormalizeLot(triggerLot*R9HedgeFraction);double maxHedge=NormalizeLot(exposure*R9BalanceCap);if(maxHedge<Lot)return(false);if(hedgeLot>maxHedge)hedgeLot=maxHedge;hedgeLot=NormalizeLot(hedgeLot);if(hedgeLot<=0.0)return(false);int hedgeTicket=SendMarket(light,hedgeLot,StringFormat("EAGOLD R9 HEDGE FROM #%d",ticket));if(hedgeTicket>0){R9MarkProcessed(hedgeTicket);g_r9HedgeActive=true;Print(EA_NAME," RULE 9 HEDGE: activation=",ticket," triggerLot=",DoubleToString(triggerLot,DigitsLots)," light=",(light==OP_BUY?"BUY":"SELL")," exposure=",DoubleToString(exposure,DigitsLots)," hedgeLot=",DoubleToString(hedgeLot,DigitsLots)," cap=",DoubleToString(R9BalanceCap,2)," newTicket=",hedgeTicket);CreateEngineActionMarker("R9","HEDGE",light,hedgeLot);return(true);}return(false);}
void Rule9DetectActivatedOrders(){if(!EnableR9Hedge)return;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder())continue;int type=OrderType();if(type!=OP_BUY&&type!=OP_SELL)continue;int ticket=OrderTicket();if(R9Processed(ticket))continue;R9HedgeFromActivatedTicket(ticket);R9MarkProcessed(ticket);}double exposure=ExposureLots();if(exposure<R9ExposureTriggerLots)g_r9HedgeActive=false;}
#endif
